# Generated by Django 4.1.3 on 2022-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
    ]
