# Generated by Django 4.1.3 on 2022-12-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0014_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
