# Generated by Django 4.1.4 on 2022-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0015_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_visits',
            field=models.IntegerField(default=0),
        ),
    ]
