# Generated by Django 4.1.4 on 2023-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_last_visit_product_num_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_resized',
            field=models.BooleanField(default=False),
        ),
    ]
