# Generated by Django 4.1.3 on 2022-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
