# Generated by Django 4.1.3 on 2022-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0003_order_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
