# Generated by Django 4.1.3 on 2022-12-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0016_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
